### PR TITLE
move to kaniko instead of s2i

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Here s2i configuration is removed and instead serving and training images are built using Dockerfiles. Seldon core libraries are added through requirements.txt for python and in Dockerfile for R. 

Build executor for builds in the cluster is kaniko, invoked from argo workflows as s2i was previously.

Docker configuration instructions changed to use .docker/config.json file (mounted as secret) as this is more portable than username and password. Instructions changed to say 'docker registry' rather than specifically dockerhub (although [my dockerhub](https://hub.docker.com/u/ryandawsonuk) is what I tested with).

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/example-seldon/37)

### CODE REVIEW

**Comment by jinchihe** [comment]
@ryandawsonuk Have you signed the CLA? See the previous comment from the googlebot.

**Comment by ryandawsonuk** [comment]
Yeah currently having some trouble with the CLA. https://github.com/kubeflow/example-seldon/pull/37.patch shows that I used my seldon.io email address for the commits and when I try to sign the CLA as part of the seldon organisation I get a message saying "It looks like you've already signed this CLA."

**Comment by ryandawsonuk** [comment]
Looks like posting a new comment prompted the CLA check to go through.

**Pull request merged**
